import type { Metadata } from "next";
import "./styles/globals.scss";
import { Analytics } from "@vercel/analytics/react";
import WebVitals from "./_lib/WebVitals";
import { GoogleTagManager } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "julianaijal.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-M8PS5F6" />
      <body>
        <WebVitals />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
