import type { NextPage } from 'next';
import Head from 'next/head';
import appConfig from '../config/app.config';
import Analytics from '../app/_lib/Analytics';
import Layout from './_components/Layout';
import Schema from './_lib/Schema';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>julianaijal.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {typeof appConfig.env.analyticsMeasurementId !== 'undefined' && (
          <Analytics
            analyticsMeasurementId={appConfig.env.analyticsMeasurementId}
          />
        )}
      </Head>
      {/* To-do:move to head */}
      <Schema/>
      <Layout />
    </>
  );
};

export default Home;
