import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { Hero } from '../components';
import appConfig from '../config/app.config';
import Analytics from '../lib/Analytics';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>julianaijal.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {process.env.NODE_ENV === 'production' &&
          typeof appConfig.env.analyticsMeasurementId !== 'undefined' && (
            <Analytics
              analyticsMeasurementId={appConfig.env.analyticsMeasurementId}
            />
          )}
      </Head>
      <main className={styles.main}>
        <Hero />
      </main>
    </>
  );
};

export default Home;
