const Schema = () => {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{
        __html: `[{"@context":"https://schema.org","@type":"Person","@id":"#Person","name":"Julian Aijal","givenName":"Julian","familyName":"Aijal","url":"https://julianaijal.com/","jobTitle":"SEO Specialist","birthDate":"1989-11-17","birthPlace":{"@type":"Place","name":"Apeldoorn"},"nationality":"NL","email":"julian.aijal@dpgmedia.nl","sameAs":["https://g.co/kgs/GRJheuw","https://amsterdamcentrum.pvda.nl/wieiswie/julian-aijal/","https://thenextweb.com/author/julianaijal","https://www.linkedin.com/in/jaijal/","https://twitter.com/Jaijal","https://www.threads.net/@julian.aijal","https://yourambassadrice.com/author/julian-aijal/","https://www.bitsoffreedom.nl/mensen/julian-aijal/","https://www.instagram.com/julian.aijal/","https://github.com/julianaijal","https://www.crunchbase.com/person/julian-aijal"],"knowsAbout":[{"@type":"Service","name":"SEO","alternateName":"Search Engine Optimization","sameAs":"https://www.wikidata.org/wiki/Q180711"},{"@type":"Service","name":"Front-End Development","sameAs":"https://www.wikidata.org/wiki/Q4130556"},{"@type":"Service","name":"Web Development","sameAs":"https://www.wikidata.org/wiki/Q386275"},{"@type":"Service","name":"programming","alternateName":"computer programming","sameAs":"https://www.wikidata.org/wiki/Q80006"},{"@type":"Service","name":"Digital Marketing","alternateName":"Online Marketing","sameAs":"https://www.wikidata.org/wiki/Q1323528"},{"@type":"Service","name":"Web Analytics","sameAs":"https://www.wikidata.org/wiki/Q10719477","isRelatedTo":[{"@id":"#google-analytics"},{"@id":"#google-tag-manager"}]}],"gender":{"@type":"GenderType","name":"male"},"image":{"@type":"ImageObject","name":"A profile picture of Julian Aijal","@id":"#image","author":{"@id":"#Person"},"url":"https://julianaijal.com/_next/static/media/julian.6deab842.svg","width":{"@type":"QuantitativeValue","value":564,"unitCode":"E37"},"height":{"@type":"QuantitativeValue","value":516,"unitCode":"E37"}},"worksFor":{"@id":"https://www.dpgmediagroup.com/nl-NL/#DPG"},"homeLocation":{"@type":"City","name":"Amsterdam","sameAs":"https://g.co/kgs/mJw8Moy"},"knowsLanguage":["en","nl"],"mainEntityOfPage":{"@type":"WebPage","@id":"https://julianaijal.com/","name":"Julian Aijal","publisher":{"@id":"#Person"},"inLanguage":"EN","isPartOf":{"@type":"WebSite","@id":"#Site","url":"https://julianaijal.com/","name":"julianaijal.com","author":{"@id":"#Person"},"publisher":{"@id":"#Person"},"creator":{"@id":"#Person"},"sdPublisher":{"@id":"#Person"}},"breadcrumb":{"@id":"#Breadcrumb"}}},{"@context":"https://schema.org","@type":"BreadcrumbList","@id":"#Breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"item":{"@type":"WebPage","@id":"https://julianaijal.com/","name":"Home"}},{"@type":"ListItem","position":2,"item":{"name":"Julian Aijal"}}]}]`,
      }}
    />
  );
};

export default Schema;
